#!/bin/sh /etc/rc.common

#Copyright (C) 2013 Ninux.org

configureNetwork()
{
	local TimeZone="CET-1CEST,M3.5.0,M10.5.0/3"
	uci set system.@system[0].hostname=Scooreggione
	uci set system.@system[0].timezone=$TimeZone
	uci del system.ntp
	uci set system.ntp=timeserver
	uci set system.ntp.enable_server=1
	uci set system.ntp.server=timeserver.ninux.org

	uci del network.lan.type

	uci set network.backbone=interface
	uci set network.backbone.proto=static
	uci set network.backbone.ipaddr=172.16.1.1
	uci set network.backbone.netmask=255.255.0.0
	uci set network.backbone.dns=8.8.8.8
	uci set network.backbone.ifname=wlan0
	uci set network.wan.proto=static

	wifidevice=$(uci show wireless | awk 'BEGIN { FS = "." };/wifi-device/{print $2}' | cut -d "=" -f1)

	uci set wireless.$wifidevice.disabled=0
	uci set wireless.$wifidevice.noscan=1
	uci set wireless.$wifidevice.distance=1000

	uci set wireless.@wifi-iface[0]=wifi-iface
	uci set wireless.@wifi-iface[0].device=$wifidevice
	uci set wireless.@wifi-iface[0].network=backbone
	uci set wireless.@wifi-iface[0].mode=sta
	uci set wireless.@wifi-iface[0].ssid=ninux.org
	uci set wireless.@wifi-iface[0].encryption=none

	uci set olsrd4.@olsrd[0]=olsrd
	uci set olsrd4.@LoadPlugin[0]=LoadPlugin
	uci set olsrd4.@LoadPlugin[0].library=olsrd_arprefresh.so.0.1
	uci set olsrd4.@LoadPlugin[1]=LoadPlugin
	uci set olsrd4.@LoadPlugin[1].library=olsrd_nameservice.so.0.3
	uci set olsrd4.@LoadPlugin[2]=LoadPlugin
	uci set olsrd4.@LoadPlugin[2].library=olsrd_txtinfo.so.0.1
	uci set olsrd4.@LoadPlugin[2].accept=127.0.0.1
	uci set olsrd4.@Interface[0]=Interface
	uci set olsrd4.@Interface[0].interface=lan backbone
	uci set olsrd6.@olsrd[0]=olsrd
	uci set olsrd6.@LoadPlugin[0]=LoadPlugin
	uci set olsrd6.@LoadPlugin[0].library=olsrd_arprefresh.so.0.1
	uci set olsrd6.@LoadPlugin[1]=LoadPlugin
	uci set olsrd6.@LoadPlugin[1].library=olsrd_nameservice.so.0.3
	uci set olsrd6.@LoadPlugin[2]=LoadPlugin
	uci set olsrd6.@LoadPlugin[2].library=olsrd_txtinfo.so.0.1
	uci set olsrd6.@LoadPlugin[2].accept=::1
	uci set olsrd6.@LoadPlugin[2].port=2007
	uci set olsrd6.@Interface[0]=Interface
	uci set olsrd6.@Interface[0].interface=lan backbone

	uci commit network
	uci commit wireless
	uci commit system
	uci commit olsrd4
	uci commit olsrd6

	echo "1" > /etc/config/ninux
}

startup=$(cat /etc/config/ninux)

# if ninux file do not exist then do nothing
test $startup || exit 0

[ "$startup" -eq "0" ] &&
{
	configureNetwork
	return 0
}
[ "$startup" -eq "1" ] &&
{
	return 0
}

