#!/bin/sh
uci set network.wan='interface'
uci set network.wan.ifname='eth0.2'
uci set network.wan.proto='pppoe'
uci set network.wan.username='adsl@alice6.it'
uci set network.wan.password='IPV6@alice6'
uci set network.wan.ipv6='0'
uci set network.wan.mtu='1492'
exit 0
